name: "java_base_applicaton"
on: 
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu:latest

    steps:
    - name: checkout and setup_java
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Verify POM File
      run: ls -la 

    - name: Build with Maven
      run:  mvn -B package --file pom.xml
    
